name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  arch_test:
    path: ../
  dio: ^5.9.0
  equatable: ^2.0.7

dev_dependencies:
  analyzer: ^9.0.0
  lints: ^6.0.0
  test: ^1.25.6
