name: arch_test
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  code_coverage: ^1.1.0
  mocktail: ^0.1.4
  pedantic: ^1.10.0
  test: ^1.17.11
dependencies: 
  equatable: ^2.0.3
  kiwi: ^3.0.0
