name: arch_test
description: Package used to create architecture tests for an application.
version: 0.1.0
homepage: https://github.com/gustavo-hillesheim/dart_arch_test

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  code_coverage: ^1.1.0
  mocktail: ^0.1.4
  pedantic: ^1.10.0
dependencies:
  analyzer: ^4.0.0
  collection: ^1.15.0
  equatable: ^2.0.3
  path: ^1.8.0
  test: ^1.0.0
  yaml: ^3.1.0
